// The AI-facing DTO surface (Phase 5.4, Part 2). Everything below this
// module — repositories, services, the database — is invisible to the AI
// platform; a `LearnerCoachingContext` is the only thing that ever crosses
// that boundary. See docs/Architecture.md → "Planned: AI Platform".

import type { AUDIENCES } from "./audiences";

export type Audience = (typeof AUDIENCES)[number];

export interface SkillSummary {
  name: string;
  subject: string;
  mastery: number;
  confidence: number;
}

export interface SubjectSummary {
  subject: string;
  mastery: number;
  confidence: number;
  accuracy: number;
}

export interface MissionSummary {
  score: number;
  totalQuestions: number;
  durationMinutes: number;
  completedAt: string;
}

/** Reused as-is from the deterministic recommendation engine — never regenerated by AI. */
export interface Recommendation {
  title: string;
  description: string;
}

export interface LearnerCoachingContext {
  schemaVersion: "1.0";
  promptVersion: "coach-v1";
  audience: Audience;
  learnerDisplayName: string;
  /** ISO 8601 date (YYYY-MM-DD) this context was generated for. */
  generatedForDate: string;
  overallMastery: number;
  overallAccuracy: number;
  totalQuestionsAnswered: number;
  currentStreak: number;
  skillsDueForReview: number;
  strongestSkills: SkillSummary[];
  focusSkills: SkillSummary[];
  subjectInsights: SubjectSummary[];
  deterministicRecommendations: Recommendation[];
  recentMission: MissionSummary | null;
  upcomingFocusSkills: string[];
}

/** The structured JSON Gemini (or any future provider) must return — nothing more, nothing less. */
export interface CoachResponse {
  headline: string;
  message: string;
  strengths: string[];
  focusAreas: string[];
  nextSteps: string[];
  disclaimer: string | null;
}
